version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=udayp@duck.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  flask-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile-flask
    image: q-self
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=api.automate.udayp.live
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.automate.udayp.live
    network_mode: bridge
    env_file:
      - .env


  vue-frontend:
    image: vue-build
    build:
      context: ./Frontend
      dockerfile: Dockerfile-react
    environment:
      - VIRTUAL_HOST=automate.udayp.live
      - LETSENCRYPT_HOST=automate.udayp.live
    network_mode: bridge
    env_file:
      - .env

volumes:
  conf:
  vhost:
  html:
  certs:
  acme: